apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: prommetricsresponse
  namespace: istio-config-default
spec:
  actions:
  - handler: handler.prometheus.istio-config-default
    instances:
    - responsesize.metric.istio-config-default
