version: '2'
services:
  details-v1:
    image: istio/examples-bookinfo-details-v1-envoy:0.2.7
    cap_add:
      - NET_ADMIN
    networks:
      default:
        aliases:
          - details
    environment:
      - SERVICE_NAME=details
      - SERVICE_TAGS=version|v1
    expose:
      - "9080"

  ratings-v1:
    image: istio/examples-bookinfo-ratings-v1-envoy:0.2.7
    cap_add:
      - NET_ADMIN
    networks:
      default:
        aliases:
          - ratings
    environment:
      - SERVICE_NAME=ratings
      - SERVICE_TAGS=version|v1
    expose:
      - "9080"

  reviews-v1:
    image: istio/examples-bookinfo-reviews-v1-envoy:0.2.7
    cap_add:
      - NET_ADMIN
    networks:
      default:
        aliases:
          - reviews
    environment:
      - SERVICE_9080_NAME=reviews
      - SERVICE_TAGS=version|v1
      - SERVICE_9443_IGNORE=1
    expose:
      - "9080"

  reviews-v2:
    image: istio/examples-bookinfo-reviews-v2-envoy:0.2.7
    cap_add:
      - NET_ADMIN
    networks:
      default:
        aliases:
          - reviews
    environment:
      - SERVICE_9080_NAME=reviews
      - SERVICE_TAGS=version|v2
      - SERVICE_9443_IGNORE=1
    expose:
      - "9080"

  reviews-v3:
    image: istio/examples-bookinfo-reviews-v3-envoy:0.2.7
    cap_add:
      - NET_ADMIN
    networks:
      default:
        aliases:
          - reviews
    environment:
      - SERVICE_9080_NAME=reviews
      - SERVICE_TAGS=version|v3
      - SERVICE_9443_IGNORE=1
    expose:
      - "9080"

  productpage-v1:
    image: istio/examples-bookinfo-productpage-v1-envoy:0.2.7
    cap_add:
      - NET_ADMIN
    networks:
      default:
        aliases:
          - productpage
    environment:
      - SERVICE_NAME=productpage
      - SERVICE_TAGS=version|v1
    ports:
      - "9081:9080"
    expose:
      - "9080"
