version: '2'
services:
  details-v1:
    image: istio/examples-bookinfo-details-v1-envoy:0.2.7
    networks:
      istiomesh:
    dns:
      - 172.28.0.1
      - 8.8.8.8
    dns_search:
        - service.consul
    cap_add:
      - NET_ADMIN
    environment:
      - SERVICE_NAME=details
      - SERVICE_TAGS=version|v1
      - SERVICE_PROTOCOL=http
    expose:
      - "9080"

  ratings-v1:
    image: istio/examples-bookinfo-ratings-v1-envoy:0.2.7
    networks:
      istiomesh:
    dns:
      - 172.28.0.1
      - 8.8.8.8
    dns_search:
        - service.consul
    cap_add:
      - NET_ADMIN
    environment:
      - SERVICE_NAME=ratings
      - SERVICE_TAGS=version|v1
      - SERVICE_PROTOCOL=http
    expose:
      - "9080"

  reviews-v1:
    image: istio/examples-bookinfo-reviews-v1-envoy:0.2.7
    networks:
      istiomesh:
    dns:
      - 172.28.0.1
      - 8.8.8.8
    dns_search:
        - service.consul
    cap_add:
      - NET_ADMIN
    environment:
      - SERVICE_9080_NAME=reviews
      - SERVICE_TAGS=version|v1
      - SERVICE_PROTOCOL=http
      - SERVICE_9443_IGNORE=1
    expose:
      - "9080"

  reviews-v2:
    image: istio/examples-bookinfo-reviews-v2-envoy:0.2.7
    networks:
      istiomesh:
    dns:
      - 172.28.0.1
      - 8.8.8.8
    dns_search:
        - service.consul
    cap_add:
      - NET_ADMIN
    environment:
      - SERVICE_9080_NAME=reviews
      - SERVICE_TAGS=version|v2
      - SERVICE_PROTOCOL=http
      - SERVICE_9443_IGNORE=1
    expose:
      - "9080"

  reviews-v3:
    image: istio/examples-bookinfo-reviews-v3-envoy:0.2.7
    networks:
      istiomesh:
    dns:
      - 172.28.0.1
      - 8.8.8.8
    dns_search:
        - service.consul
    cap_add:
      - NET_ADMIN
    environment:
      - SERVICE_9080_NAME=reviews
      - SERVICE_TAGS=version|v3
      - SERVICE_PROTOCOL=http
      - SERVICE_9443_IGNORE=1
    expose:
      - "9080"

  productpage-v1:
    image: istio/examples-bookinfo-productpage-v1-envoy:0.2.7
    networks:
      istiomesh:
        ipv4_address: 172.28.0.14
    dns:
      - 172.28.0.1
      - 8.8.8.8
    dns_search:
        - service.consul
    cap_add:
      - NET_ADMIN
    environment:
      - SERVICE_NAME=productpage
      - SERVICE_TAGS=version|v1
      - SERVICE_PROTOCOL=http
    ports:
      - "9081:9080"
    expose:
      - "9080"

networks:
  istiomesh:
    external:
      name: consul_istiomesh
